export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_RESET = "CREATE_TASK_RESET";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";
export const CREATE_TASK_CLEAR_ERROR = "CREATE_TASK_CLEAR_ERROR";

export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_RESET = "GET_TASKS_RESET";
export const GET_TASKS_ERROR = "GET_TASKS_ERROR";
export const GET_TASKS_CLEAR_ERROR = "GET_TASKS_CLEAR_ERROR";

export const GET_TASK_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASK_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASK_RESET = "GET_TASKS_RESET";
export const GET_TASK_ERROR = "GET_TASKS_ERROR";
export const GET_TASK_CLEAR_ERROR = "GET_TASKS_CLEAR_ERROR";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";
export const UPDATE_TASK_CLEAR_ERROR = "UPDATE_TASK_CLEAR_ERROR";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
export const DELETE_TASK_CLEAR_ERROR = "DELETE_TASK_CLEAR_ERROR";
